### PR TITLE
Add bonus score for line break

### PR DESCRIPTION
**Pull request by jriyyya**

### CODE REVIEW

**Comment by jriyyya** [comment]
@sourabhaa @chimosky Please Review

**Comment by chimosky** [comment]
Reviewed ce5a4dd, not tested.

Could you remove the merge commit that you've added as it has nothing to do with your PR?

**Comment by jriyyya** [comment]
Actually If I am removing that commit it is showing merge conflict

**Comment by quozl** [comment]
Under those circumstances, it may be appropriate to git pull --rebase from the origin master instead.

Work in backups of your repository until you are comfortable with git gymnastics.

**Comment by jriyyya** [comment]
Can you please explain further

**Comment by sourabhaa** [comment]
Assuming you started working on this and ghost piece feature in parallel, this branch was not up-to-date with the current master. And now you merged the master into this branch. Hence you've got the previous changes in this merge commit. Instead if you pull and rebase, the changes in your branch will be integrated to master without creating a merge commit.

As @quozl suggested, please keep a backup and experiment.

**Comment by quozl** [comment]
I agree with @sourabhaa.

The conflict can be resolved in many different ways.  The method I used was;

* `git clone`
* `git fetch origin pull/34/head`
* `git checkout -b pbs 47b2f7c`
* `git pull --rebase origin master`
* edit BlockParty.py to remove the conflict markers, given that both sides of the conflict are to be kept,
* `git add BlockParty.py`
* `git rebase --continue`

The result is my *pbs* branch is now the current master plus your code change, without any merge commit.

If I had an open pull request, as you do, I could then switch to that branch, and `git reset` to the commit hash of my *pbs* branch.  When I push that branch to GitHub, my open pull request would change and the merge commit would vanish.

Another method is to read your own commit (learn how to read diff patches), and apply it by editor to another clone.  But if not careful that could irritate your readers by causing a new pull request.

**Comment by jriyyya** [comment]
Thanks @quozl and @sourabhaa for the help, I have done it.

**Pull request merged**
