### PR TITLE
Feature: Show Highscore

### PR DESCRIPTION
**Pull request by jriyyya**
## Overview 
Added High Score feature to the block party activity by using sugar activity root for persistent high score state

## Description
I have noticed that many activities have a high score feature where they store a persistent high score state in their root folder.
This was missing in the block party activity so I used the same technique employed by other activities in which I use the activity root folder to store the current high score and I display it right above where the score was

## Screenshot

Screenshot before adding the feature
ScreenShot1

Screenshots after adding the feature

Screenshot3
Screenshot4
Screenshot2

### CODE REVIEW

**Comment by jriyyya** [comment]
@quozl Can you please review this.

**Comment by quozl** [comment]
Thanks.  Just one small thing; do not add Sugar imports to the BlockParty.py file.  At the moment that file can be run standalone, and it would be good to keep it that way.

**Comment by jriyyya** [comment]
Hi @quozl  I am not sure how I would be able to achieve this without using the `get_activity_root` function which is a part of sugar dependencies. Should I make a separate file called `HighScore.py` and import it only if we were in a sugar environment and the necessary packages were available?
Or is there some other way I'm missing?

**Comment by quozl** [comment]
In a quick search, I found some activities have score_path.py, see 2-cars-activity stick-hero-activity.  Implode activity has separation maintained, perhaps through the sugarless.py file.

You might pass a function as an additional argument to BlockParty, with a default value of None.

**Comment by jriyyya** [comment]
Yes @quozl I did look into it. Also while I was going through the Stick Hero Activity I encountered a bug and attempted to fix it
Please do check [my PR](https://github.com/sugarlabs/stick-hero-activity/pull/34) out

**Comment by jriyyya** [comment]
Hi @quozl I have made it so that the `BlockPartyActivity.py` is the one calling all sugar dependencies and the `BlockParty.py` file initializes score_path as a default value of none and if run from BlockPartyActivity it takes in score_path as the actual sugar activity root. Do check the changes.

**Comment by quozl** [comment]
Thanks.  See https://github.com/quozl/block-party-activity/commit/f1371fc2cd9a751627c8e4bc04f673b1f12718ea for my brief review comments.  I also suggest detecting and ignoring disk full, but didn't get time to test this.

**Comment by jriyyya** [comment]
thanks @quozl I have updated my code
I've also noticed various occurrences of `!=` instead of `is not` and many lines didn't comply with PEP8 standards so I might create  another PR addressing those issues as well.

**Comment by chimosky** [comment]
> thanks @quozl I have updated my code I've also noticed various occurrences of `!=` instead of `is not` and many lines didn't comply with PEP8 standards so I might create another PR addressing those issues as well.

`!=` is used to check for equality between ints typically, `not` is a logical operator that evaluates in a boolean context so if `!=` is comparing numbers then it's fine.

**Comment by jriyyya** [comment]
Understood.

**Pull request merged**
