### PR TITLE
Add Audio support

### LINKED ISSUE #4: Sound not working
Sound feature is not working, logs contain `Sound server does not respond`.

On Ubuntu 16.04 with Csound 6.05

Method used to call Csound is possibly no longer supported; there is no process listening on port 6783 on 127.0.0.1.  A more direct use of Csound may be needed.  See Music Keyboard for a direct use.

### PR DESCRIPTION
**Pull request by srevinsaju**
Fixes #4 

Audio support was not working in this activity. 
This is because at some point of history, either the sugar packaged audio or this repository had audio files necessary for it to work. The activity used a module called `cs` presumably to be csound, but it was not confirmed. As `csound 6.13` is only under testing in some devices, and not to add external dependency, `pygame.mixer` was found as a better solution to the problem.
In adopting `pygame.mixer` as an import, we would achieve:
* Lesser code size (helps excluding ctcsound modules)
* Less Hassle in Installation
* User friendly
* Handles all necessary audio files in a smooth way

The original blockparty activity didn't have audio files, although it referred to one. To make it more interesting, I have added Creative Commons Attribution'd 0.0 and 4.0 Licensed Audio files to create a whacky 8-bit rendering of the world's favorite tetris game for sugar.

### CODE REVIEW

**Comment by quozl** [comment]
Thanks.  pygame is a new dependency on most systems we deploy to, but GStreamer is always there because Sugar already depends on it.  Could you use GStreamer instead?  Look at the file aplay.py in FractionBounce, Portfolio, and Story activities.  It has a queuing feature though, rather than simultaneous mixing; do the sound effects need to be mixed (i.e. they collide in the time domain)?

**Comment by quozl** [comment]
I've asked Vadim Gerasimov if he has the sound files.

**Comment by srevinsaju** [comment]
@quozl I have ported pygame.mixer to gstreamer on https://github.com/sugarlabs/block-party-activity/pull/11/commits/89ac5756ded3e45b6a619cc6cb0c65d586c205ec . Please review. Its a bit more code than pygame.mixer ;) , but as deps are first priority :+1:

**Comment by quozl** [comment]
Vadim has provided sound files from a backup.

[BlockPartySounds.zip](https://github.com/sugarlabs/block-party-activity/files/4042279/BlockPartySounds.zip)

**Comment by srevinsaju** [comment]
@quozl I have used the original BlockParty audio from vadim on https://github.com/sugarlabs/block-party-activity/pull/11/commits/3cf6205373de64cee1b4077df92044a7249f9273 but I personally feel  changes until https://github.com/sugarlabs/block-party-activity/pull/11/commits/89ac5756ded3e45b6a619cc6cb0c65d586c205ec was better because I used 8bit classic game's sfx. Consider testing both commits to see which sounds better. But its upto you to select between the two. 
Changed other instances too.

**Comment by quozl** [comment]
Thanks.  Good progress.

* [ ] you have a Creative Commons license assertion for the audio files; as far as I know the files are under the same license that Block Party was originally released as; if you want to support both sets of audio files then provide a way to select between them?
* [ ] AudioPlayer is instantiated once for every sound effect, which is inefficient; due to deferred deleted object cleanup we'll end up with many pieces of memory and channels,
* [ ] yes, too many lines; AudioPlayer is way more complicated than it needs to be; the _playbin_ element is better.

See aplay.py in FractionBounce, Portfolio, and Story activities for how the multiple-instantiation is handled there, and how the _playbin_ element is used.

**Comment by srevinsaju** [comment]
> * [x]  you have a Creative Commons license assertion for the audio files; as far as I know the files are under the same license that Block Party was originally released as; if you want to support both sets of audio files then provide a way to select between them?

No, I have removed them. I might have dropped an info abt the license on the src which I had proabably forgotten to remove

> * [x]  AudioPlayer is instantiated once for every sound effect, which is inefficient; due to deferred deleted object cleanup we'll end up with many pieces of memory and channels,

I agree with you. changed them to a single instance

> * [x]  yes, too many lines; AudioPlayer is way more complicated than it needs to be; the _playbin_ element is better.

I tried playbin without a queue, which stops working on repeated audio play. This edit, inherited directly from APlay of FractionBounce would do the thing

**Comment by quozl** [comment]
Thanks.  Tested on Ubuntu 19.04 with Sugar 0.116.  Reviewed;

* [ ] only need one `Gst.init`,
* [ ] use `sounds` not `audio` for directory, (12 instances of sounds in my clones, 0 of audio),
* [ ] global definitions of sound file names makes it harder to understand the code, because anyone looking to find the file has to look in two places; global definitions for constants are fine when the constants are used repeatedly, but these are not,
* [ ] some whitespace changes not necessary, adds work to `git bisect` in future,
* [ ] if you can use aplay.py without changing it, please add it and import rather than in-line, to ease future maintenance,

I'd do these things myself normally as part of review, but giving you the opportunity to do so.

It may help you to look at https://github.com/sugarlabs/block-party-activity/pull/11/files to see what I'm looking at during review.

**Comment by srevinsaju** [comment]
@quozl Fixed those errors on https://github.com/sugarlabs/block-party-activity/pull/11/commits/9157c95d5951ebbf55bc3e0c233d784a3c848b9f
I have added two more blank spaces for the sake of flake8 formatting. Can't remove that. I have fixed the other things you have mentioned.

**Pull request merged**
