### PR TITLE
Port to Gtk+ 3

### PR DESCRIPTION
**Pull request by yell0wfl4sh**
Checked and tested activity properly and found no use of VanishingCursor class, so decided to remove it.
Activity works similarly even after removal of this class,

@quozl @chimosky please review!

### CODE REVIEW

**Comment by quozl** [comment]
My review blocked by licensing; working to resolve that first.

**Comment by quozl** [comment]
Agreed, the toolbar should not be removed; I can't see why you did that; the commit message is so brief.

**Comment by quozl** [comment]
@yashagrawal3 and @quozl had an impromptu meeting on #sugar;
* the patches were not rebased or squashed, and the commit messages were rather brief,
* the toolbar was not removed; it was never there; the activity does not follow the Sugar Human Interface Guidelines,
* this led to my saying the toolbar should not be removed.

I've asked that;
* the port to GTK+ 3 retain the features and behaviour of the GTK+ 2 version; which in this case means no toolbar,
* that the vanishing cursor feature be fixed; it is currently broken in the GTK+ 2 version.

It may be useful to add text like "Press Escape to quit".

**Comment by chimosky** [comment]
> It may be useful to add text like "Press Escape to quit".

Agreed, since it's already been implemented.

**Pull request merged**
