### PR TITLE
Port to Python 3 + Add README.md

### PR DESCRIPTION
**Pull request by ayushnawal**
Tested the activity before and after the changes.

Firstly, I was getting some `TypeError: list indices must be integers or slices, not float`  for `self.px` and `self.py`, fixed it by scoping them to floor int.

Working smoothly now.

@quozl please review, Thanks:)

### CODE REVIEW

**Comment by quozl** [comment]
Would it be better to recognise the division that yielded self.px and self.py was integer under Python 2, and became floating point under Python 3?  If so, the division operator could be changed instead.

See [_Check for integer divisions that have become floating point_](https://github.com/sugarlabs/sugar-docs/blob/master/src/python-porting-guide.md).

**Comment by ayushnawal** [comment]
Done and Tested :)

**Comment by quozl** [comment]
Thanks.  What are the parentheses for around the division?

```python
        self.px = (self.bw // 2) - 2
```

**Comment by ayushnawal** [comment]
Ahh sorry, I have this bad habit of using parentheses while using division operator.

I completed the game once while testing, keeping an eye on every update and the logs whether it shows any tracebacks on any event, is there anything more we need to check while testing activities? ( i mean to ask in general)

**Comment by quozl** [comment]
Thanks.  Reviewed.  Tested.  Sound did not work.

Testing is an endless list, sometimes.  When testing activities, here is what springs to mind;
* activity must start,
* activity must refresh entire display when focus is restored,
* activity must behave predictably (except where randomness is designed),
* activity must save data to journal,
* activity must restore the saved data from journal (click on the journal entry),
* other activities must be able to use saved data, if it is declared with the relevant content type,
* every coded feature should either work properly, or be removed if it cannot be fixed,
* collaboration support, if present, must function properly between two or more systems,
* activity should not consume all available battery power (e.g. pygame clock rate too high),
* activity should not contain any security vulnerabilities,
* activity should not reveal personal information.

Please review https://github.com/sugarlabs/sugar-docs/blob/master/src/contributing.md and suggest changes to add a testing checklist?

**Comment by quozl** [comment]
10ef685 ('Adjust README.md') adds author and keys to use.

**Comment by ayushnawal** [comment]
Thanks @quozl for providing me such a nice checklist, I will try to follow the same while testing.

Also, I will submit a pull request regarding adding a testing checklist in the contributing guide.

The sound not working error was reproduced with the master branch too, I saw you opened a [issue](https://github.com/sugarlabs/block-party-activity/issues/4) for the same before, will try to fix and submit a PR for the same.

**Comment by quozl** [comment]
https://github.com/sugarlabs/sugar-docs/commit/9c7a608f59eef8553aaf986212616abcac5fd2e9 ("Add testing").

**Comment by quozl** [comment]
Thanks.  I'll wait for https://github.com/sugarlabs/block-party-activity/issues/4.

**Pull request merged**
