### PR TITLE
Upstreaming v9

### PR DESCRIPTION
**Pull request by quozl**
Some changes in the Python 2 branch are potentially useful for the Python 3 branch.

### CODE REVIEW

**Comment by JuiP** [comment]
I think the changes I made in #12 should also be included in the last released python2 version of the activity as they aren't porting related changes. Can someone with rights to change master branch include them before port to python3? @quozl @chimosky

**Comment by quozl** [comment]
I don't have rights to change _master_ yet.  But you can see your changes in my [Python 2 branch](https://github.com/quozl/block-party-activity/commits/python2) underneath my changes.  So I think what you ask is already done.

**Comment by JuiP** [comment]
Yes, thankyou :)

**Comment by chimosky** [comment]
Reviewed, thanks. 

I think that since an activity toolbar has been added, the use of the escape key to quit the game should be changed to pause the game because sometimes one might decide to pause the game and not want to quit it when pressing the escape key and I've pressed it thinking it'll pause it quite a number of times.

**Comment by quozl** [comment]
Thanks.  I don't agree to change the escape key because users have already learned what it does, so an update would frustrate them.  I have no idea how you came to the conclusion that the escape key would pause the game, given that the words "Press ESC to exit" are shown.

**Comment by JuiP** [comment]
Regarding ading a pause button: I don't think we should add one because then the child can pause the game, think where to place the upcoming block and again resume. This gives the child more time to think than needed and defeats the purpose of the activity: quick thinking for block rotation and placement.

**Comment by quozl** [comment]
I don't think anyone is adding a pause button.

**Comment by chimosky** [comment]
Agreed, I'd looked at it from a different perspective earlier.

**Pull request merged**
